return {
  get = function(p)
    return {
      ["@lsp.type.boolean"] = { link = "@boolean" },
      ["@lsp.type.builtinType"] = { link = "@type.builtin" },
      ["@lsp.type.class"] = { link = "@type" },
      ["@lsp.type.comment"] = { link = "@comment" },
      ["@lsp.type.decorator"] = { link = "@attribute" },
      ["@lsp.type.deriveHelper"] = { link = "@attribute" },
      ["@lsp.type.enum"] = { link = "@type" },
      ["@lsp.type.enumMember"] = { link = "@constant" },
      ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
      ["@lsp.type.formatSpecifier"] = { link = "@punctuation.special" },
      ["@lsp.type.generic"] = { link = "@variable" },
      ["@lsp.type.interface"] = { fg = p.cyan },
      ["@lsp.type.keyword"] = { link = "@keyword" },
      ["@lsp.type.lifetime"] = { link = "@keyword.storage" },
      ["@lsp.type.macro"] = { link = "@function.macro" },
      ["@lsp.type.method"] = { link = "@function.method" },
      ["@lsp.type.namespace"] = { link = "@module" },
      ["@lsp.type.number"] = { link = "@number" },
      ["@lsp.type.operator"] = { link = "@operator" },
      ["@lsp.type.parameter"] = { fg = p.red, italic = true },
      ["@lsp.type.property"] = { fg = p.red },
      ["@lsp.type.regexp"] = { link = "@string.regexp" },
      ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
      ["@lsp.type.selfTypeKeyword"] = { link = "@variable.builtin" },
      ["@lsp.type.string"] = { link = "@string" },
      ["@lsp.type.struct"] = { link = "@type" },
      ["@lsp.type.type"] = { link = "@type" },
      ["@lsp.type.typeAlias"] = { link = "@type.definition" },
      ["@lsp.type.typeParameter"] = { fg = p.cyan, italic = true },
      ["@lsp.type.unresolvedReference"] = { undercurl = true, sp = p.red },
      ["@lsp.type.variable"] = { link = "@variable" },

      -- Type modifiers
      ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
      ["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
      ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
      ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
      ["@lsp.typemod.function.readonly"] = { fg = p.blue, bold = true },
      ["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },
      ["@lsp.typemod.keyword.injected"] = { link = "@keyword" },
      ["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
      ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
      ["@lsp.typemod.operator.injected"] = { link = "@operator" },
      ["@lsp.typemod.property.readonly"] = { fg = p.magenta },
      ["@lsp.typemod.string.injected"] = { link = "@string" },
      ["@lsp.typemod.struct.defaultLibrary"] = { link = "@type.builtin" },
      ["@lsp.typemod.variable.callable"] = { link = "@function" },
      ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
      ["@lsp.typemod.variable.injected"] = { link = "@variable" },
      ["@lsp.typemod.variable.readonly"] = { link = "@constant" },
      ["@lsp.typemod.variable.static"] = { link = "@constant" },
    }
  end
}
